[tool.poetry]
name = "fe-ec"
version = "0.1.0"
description = "Librería para la generación y envío de facturas electrónicas en Ecuador según normativa del SRI"
authors = ["OpenLatina  <openlatina.cue@gmail.com>"]
readme = "README.md"
repository = "https://github.com/angie1590/fe_ec.git"
keywords = ["facturación electrónica", "Ecuador", "SRI", "firma digital"]
packages = [{ include = "fe_ec", from = "src" }]
exclude = ["src/fe_ec/constants_copy.py"]
include = [
  { path = "src/fe_ec/utils/FirmaElectronica/**" },
  { path = "src/fe_ec/schemas/**" }
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
lxml = ">=5.2.1,<6.0"
xmlschema = "^3.4.3"
zeep = "^4.3.1"
cryptography = "<=40.0.2"
pyyaml = "^6.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
