[tool.poetry]
name = "fe-ec"
version = "0.1.0"
description = "Librería para la generación y envío de facturas electrónicas en Ecuador según normativa del SRI"
authors = ["OpenLatina  <openlatina.cue@gmail.com>"]
readme = "README.md"
repository = "https://github.com/angie1590/fe_ec.git"
keywords = ["facturación electrónica", "Ecuador", "SRI", "firma digital"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
lxml = ">=5.2.1,<6.0"
xmlschema = "^3.4.3"
zeep = "^4.3.1"
cryptography = "<=40.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"